-- Add visibility column to tags table
ALTER TABLE tags ADD (visibility VARCHAR2(255) DEFAULT 'PRIVATE' NOT NULL);

-- Friend table
CREATE TABLE friend (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id NUMBER NOT NULL,
    following_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_friend_follower FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_friend_following FOREIGN KEY (following_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_friend_follower_following UNIQUE (follower_id, following_id)
);
Drop table friend;
drop table notification;
-- Notification table
CREATE TABLE notification (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id NUMBER NOT NULL,
    sender_id NUMBER NOT NULL,
    notification_type VARCHAR2(255) NOT NULL,
    is_read NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_notification_is_read CHECK (is_read IN (0, 1)), -- 0 for false, 1 for true
    CONSTRAINT fk_notification_recipient FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_sender FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE
);