CREATE TABLE i_log (
    -- 기본 키, 1부터 자동으로 1씩 증가하는 숫자 (number(19)와 동일)
                       id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 작성자 ID, users 테이블의 id를 참조하는 외래 키
                       user_id NUMBER(19) NOT NULL,

    -- 일기 날짜, "YYYY-MM-DD" 형식을 저장하기에 최적화된 타입
                       i_log_date DATE NOT NULL,

    -- 일기 본문, 3000자를 초과할 수 있으므로 CLOB 타입 사용
                       content VARCHAR2(3000 CHAR) NOT NULL,

    -- 대표 이미지 URL, 사진이 없을 수도 있으므로 NULL 허용
                       img_url VARCHAR2(2048 CHAR),

    -- 생성 시각, 레코드 생성 시 자동으로 현재 시간이 기록됨
                       created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    -- 좋아요 수, 기본값 0
                       like_count NUMBER DEFAULT 0 NOT NULL,

    -- 댓글 수, 기본값 0
                       comment_count NUMBER DEFAULT 0 NOT NULL,

    -- 공개 여부
                       visibility NUMBER(1) DEFAULT 0 NOT NULL,

    -- 친구 태그 (user_id 나열)
                       friend_tags VARCHAR2(2000),

    -- 일반 태그 / 해시태그
                       tags VARCHAR2(1000),

    -- 외래 키 제약 조건 설정 (users 테이블이 있다는 가정 하에)
                       CONSTRAINT fk_i_log_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,

    --  특정 사용자는 하루에 하나의 일기만 작성 가능하도록 UNIQUE 제약 조건 추가
                       CONSTRAINT uq_i_log_user_date UNIQUE (user_id, i_log_date)
);

DELETE USERS where ID = 3;