CREATE TABLE ilog_comment_likes (
    -- PK, 자동 증가
                                    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 댓글 FK
                                    comment_id NUMBER(19) NOT NULL,
    -- 좋아요 누른 사용자 FK
                                    user_id NUMBER(19) NOT NULL,
    -- 생성 시각
                                    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    -- 제약 조건
    -- 댓글이 삭제되면 좋아요도 삭제
                                    CONSTRAINT fk_like_comment FOREIGN KEY (comment_id) REFERENCES ilog_comments(id) ON DELETE CASCADE,
    -- 사용자가 탈퇴하면 좋아요도 삭제
                                    CONSTRAINT fk_like_user FOREIGN KEY (user_id) REFERENCES user_profile(user_id) ON DELETE CASCADE,
    -- 한 유저가 같은 댓글에 중복 좋아요 불가
                                    CONSTRAINT uq_comment_like UNIQUE (comment_id, user_id)
);