CREATE TABLE ilog_comments (
    -- PK, 자동 증가
                               id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 일기 FK
                               ilog_id NUMBER(19) NOT NULL,
    -- 작성자 FK
                               user_id NUMBER(19) NOT NULL,
    -- 부모 댓글 FK (대댓글용)
                               parent_comment_id NUMBER(19), -- NULL이면 "일기 댓글", 값 있으면 "대댓글"
    -- 댓글 내용
                               content VARCHAR2(300) NOT NULL,
    -- 생성 시각
                               created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    -- 삭제 여부 (논리적 삭제용)
                               is_deleted NUMBER(1) DEFAULT 0 NOT NULL,
    -- 좋아요 수 (조회 성능 최적화용)
                               like_count NUMBER(10) DEFAULT 0 NOT NULL,

    -- 제약 조건
                               CONSTRAINT fk_comment_ilog FOREIGN KEY (ilog_id) REFERENCES i_log(id) ON DELETE CASCADE,
                               CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES user_profile(user_id) ON DELETE CASCADE,
    -- 부모 댓글 참조
                               CONSTRAINT fk_parent_comment FOREIGN KEY (parent_comment_id) REFERENCES ilog_comments(id)
);