CREATE TABLE likes (
    -- 기본 키, 1부터 자동으로 1씩 증가
                       id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 좋아요를 누른 사용자의 ID, user_profile 테이블 참조
                       user_id NUMBER(19) NOT NULL,

    -- 좋아요가 달린 일기의 ID, i_log 테이블 참조
                       ilog_id NUMBER(19) NOT NULL,

    -- 생성 시각, 레코드 생성 시 자동으로 현재 시간이 기록됨
                       created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    -- 외래 키 제약 조건: user_profile 테이블의 user_id 참조
    -- 사용자가 탈퇴하면(user_profile 레코드 삭제) 해당 사용자의 좋아요 기록도 함께 삭제됩니다.
                       CONSTRAINT fk_likes_user FOREIGN KEY (user_id) REFERENCES user_profile(user_id) ON DELETE CASCADE,

    -- 외래 키 제약 조건: i_log 테이블의 id 참조
    -- 일기가 삭제되면(i_log 레코드 삭제) 해당 일기의 좋아요 기록도 함께 삭제됩니다.
                       CONSTRAINT fk_likes_ilog FOREIGN KEY (ilog_id) REFERENCES i_log(id) ON DELETE CASCADE,

    -- 유니크 제약 조건: 한 사용자가 같은 일기에 두 번 좋아요를 누를 수 없도록 방지
                       CONSTRAINT uq_likes_user_ilog UNIQUE (user_id, ilog_id)
);