-- 기존 schedules 테이블 (tags 컬럼이 tag_id로 변경됨)
CREATE TABLE schedules (
    -- 기본 정보
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) NOT NULL,
    tag_id NUMBER(19), -- 태그 ID (tags 테이블과 연결), 태그는 선택사항일 수 있으므로 NULL 허용

    -- 일정 내용
    title VARCHAR2(255) NOT NULL,
    location VARCHAR2(255),
    description CLOB,

    -- 시간 정보
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    is_all_day NUMBER(1) DEFAULT 0 NOT NULL,

    -- 반복 정보
    rrule VARCHAR2(255),

    -- 메타데이터
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    -- 외래 키 제약 조건
    CONSTRAINT fk_schedules_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_schedules_tag_id FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE SET NULL, -- 태그 삭제 시, 해당 스케줄의 태그 정보만 NULL로 변경
    CONSTRAINT chk_schedules_is_all_day CHECK (is_all_day IN (0, 1))
);

DROP table SCHEDULES;